version: "3.9"
services:
  app:
    build:
      context: ./ses-sales-support-tool
      dockerfile: Dockerfile
    container_name: ses-sales-support-tool
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=docker
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - PORT=8080
    depends_on: []
    restart: unless-stopped
